#nginx:
#    image: nginx:latest
#    ports:
#        - '80:80'
#    volumes:
#        - ./nginx:/etc/nginx/conf.d
#        - ./logs/nginx:/var/log/nginx
#        - /var/www/html:/var/www/html
#    links:
#        - myphp
#    restart: always



mysql:
    image: mariadb
    ports:
        - '3306:3306'
    volumes:
        - ./db-data:/var/lib/mysql
    environment:
        - MYSQL_ROOT_PASSWORD=aqwe123
    restart: always



myphp:
    image: php:fpm
    ports:
        - '9000:9000'
    volumes:
        - /var/www/html:/var/www/html
    environment:
        - myphp_DB_NAME=wpdb
        - myphp_TABLE_PREFIX=wp_
        - myphp_DB_HOST=mysql
        - myphp_DB_PASSWORD=aqwe123
    links:
        - mysql
    restart: always
